language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libnetcdf-dev
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
